logging: true
#mute server step updates in terminal (useful if using docker)
muted: true

log_dir: "./logs"
model_dir: "./models"
log_steps: 50

#cpu OR gpu
device: gpu
client_total: 5
epoch: 5
round: 3
batch_size: 32

patience: 0
cut_layer: 4
test_cut_layer: 4

# n for no_split, s: for getting split i from data server, Any number for the number of i.i.d splits.
split_type: s
split_server: 
  server_ip: tcp://localhost
  server_start_port: 5555
fed_server:
  server_ip: tcp://localhost
  server_start_port: 4445
data_server:
  server_address: http://localhost:8000/
  output_file: quantity_skew_minsize_dirichlet.pkl