services:
  fed:
    image: split_learning
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --fed --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  split:
    image: split_learning
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --server --extra 4,4,4,4,4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client1:
    image: split_learning
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --client 1 --extra 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client2:
    image: split_learning
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --client 2 --extra 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client3:
    image: split_learning
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --client 3 --extra 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml


  client4:
    image: split_learning
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --client 4 --extra 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml


  client5:
    image: split_learning
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1_custom_cut --client 5 --extra 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml      