services:
  fed:
    image: split-learning
    network_mode: host
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --fed --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  split:
    image: split-learning
    network_mode: host
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --server --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client1:
    image: split-learning
    network_mode: host
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --client 1 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client2:
    image: split-learning
    network_mode: host
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --client 2 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml

  client3:
    image: split-learning
    network_mode: host
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --client 3 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml


  client4:
    image: split-learning
    network_mode: host
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --client 4 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml


  client5:
    image: split-learning
    network_mode: host
    cpus: 2
    mem_limit: 2g
    runtime: nvidia
    gpus: all
    command: python -m split-learning --mode splitfed_v1 --client 5 --config config.yaml
    working_dir: /src
    volumes:
      - ./logs:/src/logs
      - ./models:/src/models
      - ./config.yaml:/src/config.yaml      