logging: false
log_steps: 50
#cpu OR gpu
device: cpu
cut_layer: 3
epoch: 5
batch_size: 128
# n for no_split, s: for getting split i from data server, Any number for the number of i.i.d splits.
split_type: s
split_server: 
  server_ip: tcp://127.0.0.1
  server_start_port: 5555